
-- Drop the unique INDEX (not constraint) on code+tenant
DROP INDEX IF EXISTS uq_service_catalog_code_tenant;

-- Insert 55 new services (old ones already deactivated by previous migration)
INSERT INTO service_catalog (code, name, default_unit, default_price, is_active) VALUES
('Design & Consulting', '2D/3D garden design with realistic renderings', 'job', 300, true),
('Design & Consulting', 'Consulting in choosing plants and materials', 'hour', 50, true),
('Design & Consulting', 'Green space planning and optimization', 'job', 200, true),
('Design & Consulting', 'Site analysis and soil testing', 'job', 100, true),
('Design & Consulting', 'Other design or consulting services', 'hour', 75, true),
('Garden Landscaping & Green Spaces', 'Roll turf installation', 'sqm', 10, true),
('Garden Landscaping & Green Spaces', 'Lawn seeding', 'sqm', 2, true),
('Garden Landscaping & Green Spaces', 'Lawn overseeding', 'sqm', 1, true),
('Garden Landscaping & Green Spaces', 'Planting and replanting', 'job', 20, true),
('Garden Landscaping & Green Spaces', 'Automatic irrigation systems', 'job', 400, true),
('Garden Landscaping & Green Spaces', 'Ambient lighting systems', 'job', 100, true),
('Garden Landscaping & Green Spaces', 'Decorative alleys and borders', 'm', 40, true),
('Garden Landscaping & Green Spaces', 'Decorative mulching', 'sqm', 15, true),
('Garden Landscaping & Green Spaces', 'Installation of decorative elements', 'job', 50, true),
('Garden Landscaping & Green Spaces', 'Hardscaping installation', 'job', 2000, true),
('Garden Landscaping & Green Spaces', 'Water features installation', 'job', 1500, true),
('Garden Landscaping & Green Spaces', 'Drainage solutions', 'm', 50, true),
('Garden Landscaping & Green Spaces', 'Other landscaping or construction services', 'job', 500, true),
('Regular Maintenance', 'Lawn mowing', 'sqm', 0.50, true),
('Regular Maintenance', 'Lawn scarification', 'sqm', 1, true),
('Regular Maintenance', 'Lawn aeration', 'sqm', 1, true),
('Regular Maintenance', 'Lawn edging', 'm', 2, true),
('Regular Maintenance', 'Lawn repair', 'sqm', 10, true),
('Regular Maintenance', 'Lawn topdressing', 'sqm', 2, true),
('Regular Maintenance', 'Weed removal', 'hour', 30, true),
('Regular Maintenance', 'Selective or total herbiciding', 'sqm', 1, true),
('Regular Maintenance', 'Foliar fertilizer application', 'sqm', 1, true),
('Regular Maintenance', 'Soil fertilization', 'sqm', 1, true),
('Regular Maintenance', 'Phytosanitary treatments', 'job', 50, true),
('Regular Maintenance', 'Hedge trimming', 'm', 5, true),
('Regular Maintenance', 'Shrub and tree pruning', 'job', 20, true),
('Regular Maintenance', 'Topiary trimming', 'job', 30, true),
('Regular Maintenance', 'Protecting sensitive plants for winter', 'job', 10, true),
('Regular Maintenance', 'General cleanup', 'hour', 40, true),
('Regular Maintenance', 'Alley cleaning', 'hour', 30, true),
('Regular Maintenance', 'Pressure washing paving', 'sqm', 2, true),
('Regular Maintenance', 'Organic lawn care', 'sqm', 2, true),
('Regular Maintenance', 'Other maintenance services', 'hour', 35, true),
('Irrigation System Maintenance', 'Checking and adjusting sprinklers', 'job', 60, true),
('Irrigation System Maintenance', 'Cleaning nozzles and filters', 'hour', 50, true),
('Irrigation System Maintenance', 'Repairing existing irrigation systems', 'hour', 60, true),
('Irrigation System Maintenance', 'Winterizing systems', 'job', 100, true),
('Irrigation System Maintenance', 'Smart controller upgrades', 'job', 150, true),
('Irrigation System Maintenance', 'Other irrigation maintenance', 'hour', 55, true),
('Special & Seasonal Services', 'Clearing weeds and spontaneous vegetation', 'sqm', 3, true),
('Special & Seasonal Services', 'Shredding plant debris', 'hour', 30, true),
('Special & Seasonal Services', 'Soil revitalization', 'sqm', 5, true),
('Special & Seasonal Services', 'Insect control', 'job', 75, true),
('Special & Seasonal Services', 'Spring/fall garden preparation', 'job', 200, true),
('Special & Seasonal Services', 'Periodic maintenance subscription', 'flat', 150, true),
('Special & Seasonal Services', 'Stump grinding and removal', 'job', 150, true),
('Special & Seasonal Services', 'Snow removal and ice management', 'hour', 50, true),
('Special & Seasonal Services', 'Gutter cleaning', 'm', 3, true),
('Special & Seasonal Services', 'Other special or seasonal services', 'job', 100, true);
